# vim: ft=yaml
---
driver:
  name: docker

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - test.mockup
        - artifactory
  pillars:
    top.sls:
      base:
        "*":
          - artifactory

platforms:
  - name: debian-8

suites:
  - name: default
    provisioner:
      pillars:
        artifactory.sls:
          artifactory:
            enabled: true

  - name: oss
    provisioner:
      pillars-from-files:
        artifactory.sls: pillar-oss.sls

  - name: pro
    provisioner:
      pillars-from-files:
        artifactory.sls: pillar-pro.sls
