# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - test.mockup
        - artifactory
  pillars:
    top.sls:
      base:
        "*":
          - artifactory

platforms:
  - name: bento/debian-8.7

suites:
  - name: default
    provisioner:
      pillars:
        artifactory.sls:
          artifactory:
            enabled: true

  - name: oss
    driver:
      network:
        - ["forwarded_port", {guest: 8081, host: 8081}]
    provisioner:
      pillars-from-files:
        artifactory.sls: pillar-oss.sls

  - name: pro
    driver:
      network:
        - ["forwarded_port", {guest: 8081, host: 8082}]
    provisioner:
      pillars-from-files:
        artifactory.sls: pillar-pro.sls
