sudo: required
dist: trusty
language: ruby

bundler_args: --without='vagrant linode'

services:
  - docker

cache:
  bundler: true
  directories:
    - /var/lib/docker

env:
  matrix:
  - INSTANCE=default
  - INSTANCE=oss
  - INSTANCE=pro

script:
  - bundle exec docker version
  - bundle exec kitchen --version
  - KITCHEN_LOCAL_YAML=.kitchen-docker.yml kitchen test ${INSTANCE}

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
